### ISSUE TITLE
Last Rush - Reorder

### ISSUE THREAD

**Issue by TommaruX3700** [TommaruX3700/EPS-personalModelTest#34]
Dividersi il lavoro per portare un alfa.
Componenti da portare a termine: 
---
### Application Model: (Tommaso e Federico): 
- [x] assigned
#### TODO:
- [ ] Nesting
- [ ] Multithreading 
- [ ] Generazione Pallet

---
### Interfaccia utente: (Mioli schiavo)
- [x] assigned
#### TODO:
- [ ] Generazione bolle pdf
- [ ] Modalità secondaria x richiesta lista di pacchi da database 
- [ ] Generazione immagini nesting

---
### Database (Bicego)
- [x] assigned
#### TODO:
- [ ] Mock-data pacchi
- [ ] Test struttura e query
- [ ] Implementazione ambiente di test (forse VM o Docker)
